.\" Copyright (C), 2019, Chang-Ning Tsai
.TH CHANG-NING 7 "" "" "About Me"
.SH NAME
Chang-Ning Tsai \- a code farmer
.SH SYNOPSIS
chang-ning <experience>
.SH "SKILLS"
.SS "Languages"
Python, C/C++, Javascript/Nodejs, Bash, HTML, CSS
.SS "Others"
Docker, Kubernetes, Jenkins, Wireshark, Amazon Web Service
.SH "WORK EXPERIENCE"
.SS "Synology Inc."
.TP 10
.I "Netatalk"
Maintained the open source project, Netatalk, which is the implementation
of Apple File Protocol server and integrated features such as Mac
Spotlight Search, reflink copy, and profiling switch to Network
Attached Storage (NAS).
.TP
.I "Avahi"
Implemented Multicast DNS CNAME record to Avahi, which is the open source
MDNS (Mac Bonjour) project and tuned configurations for integrating
different platforms of Network Attached Storage.
.TP
.I "CI/CD"
Used Docker/Kubernetes to implement Continuous Integration System for
quality control as well as wrote many regression/performance tests for
accelerating development schedule.
.TP
.I "Support"
Migrate self-host support service from a single machine to Amazon Web
Service and used CodePipeline, Lambda, DynamoDB, Elastic Beanstalk,
ElastiCache, and CloudFormation to enhance the realibility of the
support srvice.
.SS "LeaderG Inc."
.TP
.I MobileApp
Participate in developing iPhone mobile apps such as Asante Genie Home
Gateway and E-Book.
