.\" Copyright (C), 2019, Chang-Ning Tsai
.TH CHANG-NING 7 "2019-05-02"
.SH NAME
Chang-Ning Tsai \- a code farmer
.SH DESCRIPTION
.B Skills
    C/C++, Python, Bash, Javascripts
.PP
.B Open Source Contribution
    flask-seasurf
    blessed-contrib
.PP
.B Work Experience
    Product Developer /
.UR https://www.synology.com
Synology
.UE
/ Taipei, Taiwan / 2015-2018
    Mobile Developer /
.UR https://www.leaderg.com
LeaderG
.UE
/ Taipei, Taiwan / 2013-2014
.PP
.B Talks
.UR http://pycon.hk/2016/program/how-to-use-coroutine-to-build-a-socket-server
    How to use coroutine to build a socket server?
.UE
/ PyCon HK 2016 / Hong Kong, China
.SH SEE ALSO
    E-mail: spiderpower02@gmail.com
    GitHub:
.UR https://github.com/crazyguitar
crazyguitar
.UE
    LinkedIn:
.UR https://www.linkedin.com/in/chang-ning-tsai-88bb2899
chang-ning
.UE
